# Generated by Django 4.1.2 on 2022-10-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
