# Generated by Django 4.1.2 on 2022-10-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_delete_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.IntegerField(choices=[(1, 'Stripe'), (2, 'PayPal')]),
        ),
    ]
